### ISSUE TITLE
reduce clone and own in the test harness (applies to other repos also)

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-runtime-php#5]
the test directory 4 files, only 1 of which is relevant to testing this runtime; the rest are cloned from openwhisk repo and provide the test harness; we need to remove this duplication since it's a maintenance headache in general.

perhaps using the maven dependences is a way of doing that?

**Comment by chetanmeh** [comment]
So far there was a gradle project dependency on core tests which is being now replaced with Maven dependency via #3. But in both cases we can make use of existing test in core and need not copy it

**Comment by csantanapr** [comment]
This is nuked now 🎉
