### ISSUE TITLE
Some source files miss Apache license headers

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-runtime-php#8]
Following [Apache license header guideline](http://www.apache.org/legal/src-headers.html), **all human-readable Apache-developed files that are included within a distribution must include the header text with few exceptions**. You can find few exceptions here: [which files do not require a license header](http://www.apache.org/legal/src-headers.html#faq-exceptions).

I used Apache Rat to check this repository after excluding a few files, and I got this report. We need to add Apache licensing header to those files.
```
Unapproved licenses:

  openwhisk-runtime-php/core/php7.1Action/Dockerfile
  openwhisk-runtime-php/tests/src/test/resources/application.conf
  openwhisk-runtime-php/ansible/environments/local/group_vars/all
  openwhisk-runtime-php/ansible/environments/local/hosts
```

The excluded files are:
```
**/*.json
**/**.gradle
**/gradlew
**/gradle/**
**/.**
**/templates/**
**/*.j2.*
**/.github/**
**/auth.whisk.system
**/auth.guest
**/i18n_resources.go
```

**Comment by daisy-ycguo** [comment]
I suggest to add below files to excluded file list, because they are configuration files with few creativity.

```
  openwhisk-runtime-php/tests/src/test/resources/application.conf
  openwhisk-runtime-php/ansible/environments/local/group_vars/all
  openwhisk-runtime-php/ansible/environments/local/hosts
```

**Comment by csantanapr** [comment]
I think is done now
